name: panorama
description: Panorama -- A 360-degree panorama viewer.
version: 0.2.0
homepage: https://github.com/zesage/panorama

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cube: ^0.0.6
  motion_sensors: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
